// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class CommentRequest (
  val idPost: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommentRequest {
      val idPost = pigeonVar_list[0] as String
      return CommentRequest(idPost)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      idPost,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PostDetail (
  val postId: Long,
  val id: Long,
  val name: String,
  val email: String,
  val body: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PostDetail {
      val postId = pigeonVar_list[0] as Long
      val id = pigeonVar_list[1] as Long
      val name = pigeonVar_list[2] as String
      val email = pigeonVar_list[3] as String
      val body = pigeonVar_list[4] as String
      return PostDetail(postId, id, name, email, body)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      postId,
      id,
      name,
      email,
      body,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommentResponse (
  val results: List<PostDetail>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommentResponse {
      val results = pigeonVar_list[0] as List<PostDetail>
      return CommentResponse(results)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      results,
    )
  }
}
private open class PostDetailPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommentRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PostDetail.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommentResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CommentRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PostDetail -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CommentResponse -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PostDetailApi {
  fun search(request: CommentRequest, callback: (Result<CommentResponse>) -> Unit)

  companion object {
    /** The codec used by PostDetailApi. */
    val codec: MessageCodec<Any?> by lazy {
      PostDetailPigeonCodec()
    }
    /** Sets up an instance of `PostDetailApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PostDetailApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pin_app.PostDetailApi.search$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CommentRequest
            api.search(requestArg) { result: Result<CommentResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
