// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class CommentRequest {
  CommentRequest({
    required this.idPost,
  });

  String idPost;

  Object encode() {
    return <Object?>[
      idPost,
    ];
  }

  static CommentRequest decode(Object result) {
    result as List<Object?>;
    return CommentRequest(
      idPost: result[0]! as String,
    );
  }
}

class PostDetail {
  PostDetail({
    required this.postId,
    required this.id,
    required this.name,
    required this.email,
    required this.body,
  });

  int postId;

  int id;

  String name;

  String email;

  String body;

  Object encode() {
    return <Object?>[
      postId,
      id,
      name,
      email,
      body,
    ];
  }

  static PostDetail decode(Object result) {
    result as List<Object?>;
    return PostDetail(
      postId: result[0]! as int,
      id: result[1]! as int,
      name: result[2]! as String,
      email: result[3]! as String,
      body: result[4]! as String,
    );
  }
}

class CommentResponse {
  CommentResponse({
    required this.results,
  });

  List<PostDetail> results;

  Object encode() {
    return <Object?>[
      results,
    ];
  }

  static CommentResponse decode(Object result) {
    result as List<Object?>;
    return CommentResponse(
      results: (result[0] as List<Object?>?)!.cast<PostDetail>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CommentRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is PostDetail) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is CommentResponse) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return CommentRequest.decode(readValue(buffer)!);
      case 130: 
        return PostDetail.decode(readValue(buffer)!);
      case 131: 
        return CommentResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PostDetailApi {
  /// Constructor for [PostDetailApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PostDetailApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CommentResponse> search(CommentRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pin_app.PostDetailApi.search$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CommentResponse?)!;
    }
  }
}
