// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct PostDetail {
  var postId: Int64
  var id: Int64
  var name: String
  var email: String
  var body: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PostDetail? {
    let postId = pigeonVar_list[0] as! Int64
    let id = pigeonVar_list[1] as! Int64
    let name = pigeonVar_list[2] as! String
    let email = pigeonVar_list[3] as! String
    let body = pigeonVar_list[4] as! String

    return PostDetail(
      postId: postId,
      id: id,
      name: name,
      email: email,
      body: body
    )
  }
  func toList() -> [Any?] {
    return [
      postId,
      id,
      name,
      email,
      body,
    ]
  }
}

private class PostDetailApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PostDetail.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PostDetailApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PostDetail {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PostDetailApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PostDetailApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PostDetailApiPigeonCodecWriter(data: data)
  }
}

class PostDetailApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PostDetailApiPigeonCodec(readerWriter: PostDetailApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DetailApi {
  func search(baseUrl: String, endpoint: String, postId: Int64, completion: @escaping (Result<[PostDetail], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DetailApiSetup {
  static var codec: FlutterStandardMessageCodec { PostDetailApiPigeonCodec.shared }
  /// Sets up an instance of `DetailApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DetailApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let searchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pin_app.DetailApi.search\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let baseUrlArg = args[0] as! String
        let endpointArg = args[1] as! String
        let postIdArg = args[2] as! Int64
        api.search(baseUrl: baseUrlArg, endpoint: endpointArg, postId: postIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      searchChannel.setMessageHandler(nil)
    }
  }
}
